from pathlib import Path
root=Path('/home/nmaldaner/projetos/loop-r')
en={
'Curso para donos e gestores 40+: monte um loop de melhoria com IA no seu negócio — evidência, hipótese, experimento, decisão com cartão e botão de voltar atrás. Sem vídeo, sem instalar nada.':'A course for business owners and managers aged 40+: build an AI improvement loop for your business — evidence, hypotheses, experiments, card-based decisions, and rollback. No videos or installation required.',
'LOOP-R: Sua Empresa que Aprende Sozinha':'LOOP-R: The Business That Learns on Its Own',
'IA para o seu negócio · nível iniciante':'AI for your business · beginner level',
'Sua empresa usa IA mil vezes.':'Your business uses AI a thousand times.',
'Por que continua igual?':'Why does nothing change?',
'Ao final você terá um loop de melhoria rodando em um processo do seu negócio, com registro do que foi testado e um botão de voltar atrás. Sem vídeo, no seu tempo, direto no navegador.':'By the end, you will have an improvement loop running on one of your business processes, with a record of what was tested and a rollback button. No videos; learn at your own pace in your browser.',
'começar pela trilha 1 →':'start with track 1 →','~20 min por sessão · 5 trilhas · 21 aulas · sem instalar nada · funciona no celular e no computador':'~20 min per session · 5 tracks · 21 lessons · no installation · works on phone and computer',
'O que você sai sabendo fazer':'What you will know how to do','Resultado, não teoria':'Results, not theory',
'Escrever o objetivo com número':'Write a measurable goal','— "de 3 em 100 para 5 em 100", e não "melhorar as vendas". É a primeira das cinco respostas que montam o loop.':'— “from 3 out of 100 to 5 out of 100,” not “improve sales.” This is the first of the five answers that set up the loop.',
'Transformar resultado em evidência':'Turn results into evidence','— uma planilha de registro, uma linha por proposta, chamado ou post, que o loop lê toda semana.':'— a tracking spreadsheet, with one row per proposal, support ticket, or post, which the loop reads each week.',
'Definir o que nunca muda sozinho':'Define what must never change on its own','— os guarda-corpos: o que a IA não pode tocar e o que não pode piorar enquanto melhora o resto.':'— the guardrails: what AI cannot touch and what must not get worse while the rest improves.',
'Decidir com o cartão de cinco linhas':'Decide with the five-line card','— aprovar, rejeitar ou esperar mais dados, sabendo qual quantidade prova e qual só parece.':'— approve, reject, or wait for more data, knowing which sample size provides evidence and which only looks convincing.',
'Dizer o que o loop não garante':'Know what the loop does not guarantee','— e por isso confiar no que ele garante: nenhuma versão pior entra, tudo fica registrado, dá para voltar.':'— so you can trust what it does guarantee: no worse version goes live, everything is recorded, and you can roll back.',
'Este curso não promete que o seu número sobe. Promete que ele não cai por decisão de um sistema, que cada tentativa fica registrada, e que você saberá dizer qual evidência faria você descartar a própria ideia.':'This course does not promise that your numbers will rise. It promises they will not fall because a system decided so, that every attempt will be recorded, and that you will know what evidence would make you discard your own idea.',
'Para quem é':'Who this is for','Feito para o seu momento':'Made for where you are now','é para você se':'this is for you if','não é para você se':'this is not for you if',
'Você é dona de clínica, corretor de imóveis, gestor de suporte — ou toca qualquer negócio onde a mesma tarefa se repete toda semana — e já usa IA para fazer propostas, respostas ou posts.':'You own a clinic, sell real estate, manage customer support, or run any business where the same task repeats every week — and already use AI to write proposals, replies, or posts.',
'Você sente que a IA faz, mas nada melhora: a proposta de hoje começa do zero, como a de seis meses atrás.':'You feel AI gets things done, but nothing improves: today’s proposal starts from scratch, just like the one from six months ago.',
'Você usa WhatsApp, planilha e um chat de IA. Nunca abriu uma tela preta de comandos e não pretende.':'You use WhatsApp, spreadsheets, and an AI chat. You have never opened a black command screen and do not plan to.',
'Você tem 20 minutos por sessão e prefere sair de cada aula com uma coisa preenchida.':'You have 20 minutes per session and prefer to finish each lesson with something filled in.',
'Você quer aprender a programar agentes ou a integrar sistemas — este curso é sobre o método e a decisão, não sobre código.':'You want to learn to program agents or integrate systems — this course teaches the method and decision-making, not coding.',
'Você quer um curso de prompts. Aqui os prompts são peças de um sistema, não o sistema.':'You want a prompt-writing course. Here, prompts are parts of a system, not the system itself.',
'Você quer um curso com vídeo-aula tradicional.':'You want a course with traditional video lessons.','Trilhas':'Tracks','Do diagnóstico ao seu loop montado':'From diagnosis to your working loop',
'Por que sua empresa não melhora':'Why your business does not improve','Saia com a lista das cinco tarefas que "terminam ali" no seu negócio e o seu nível de maturidade (1 a 5) marcado.':'Leave with a list of five tasks in your business that “end there” and your maturity level marked (1 to 5).',
'O LOOP-R: localizar, operar, observar, propor, reforçar':'LOOP-R: locate, operate, observe, propose, reinforce','Saia com o objetivo escrito com número, dez linhas na planilha de registro e três hipóteses no formato SE… ENTÃO… PORQUE.':'Leave with a measurable goal, ten rows in the tracking spreadsheet, and three hypotheses in IF… THEN… BECAUSE format.',
'Os assistentes do loop':'The loop assistants','Saia com os guarda-corpos escritos — três coisas que nunca mudam sozinhas, duas que não podem piorar — e a primeira linha da sua memória.':'Leave with written guardrails — three things that never change on their own and two that must not get worse — and the first entry in your memory.',
'Medir de verdade':'Measure for real','Saia sabendo qual quantidade prova, com uma lista de conferência sim/não para o seu artefato, e tendo decidido sobre três cartões reais.':'Leave knowing what sample size provides evidence, with a yes/no checklist for your work product, and having decided on three real cards.',
'Da tarefa à empresa':'From task to business','Saia com a ficha do loop completa — as cinco respostas — e o primeiro cartão de decisão preenchido. É a entrega final.':'Leave with a complete loop profile — all five answers — and your first completed decision card. This is your final deliverable.',
'aulas':'lessons','começar agora →':'start now →','Quer ver a ferramenta antes do curso? O guia do LOOP-R está em':'Want to see the tool before taking the course? The LOOP-R guide is at',
'LOOP-R: Sua Empresa que Aprende Sozinha · INEMA.CLUB PRO':'LOOP-R: The Business That Learns on Its Own · INEMA.CLUB PRO'
}
es={
'Curso para donos e gestores 40+: monte um loop de melhoria com IA no seu negócio — evidência, hipótese, experimento, decisão com cartão e botão de voltar atrás. Sem vídeo, sem instalar nada.':'Curso para propietarios y gestores de 40 años o más: crea un ciclo de mejora con IA para tu negocio — evidencia, hipótesis, experimentos, decisiones con tarjeta y opción para volver atrás. Sin videos ni instalaciones.',
'LOOP-R: Sua Empresa que Aprende Sozinha':'LOOP-R: Tu empresa aprende por sí sola','IA para o seu negócio · nível iniciante':'IA para tu negocio · nivel inicial',
'Sua empresa usa IA mil vezes.':'Tu empresa usa IA mil veces.','Por que continua igual?':'¿Por qué todo sigue igual?',
'Ao final você terá um loop de melhoria rodando em um processo do seu negócio, com registro do que foi testado e um botão de voltar atrás. Sem vídeo, no seu tempo, direto no navegador.':'Al final tendrás un ciclo de mejora funcionando en un proceso de tu negocio, con un registro de lo probado y una opción para volver atrás. Sin videos, a tu ritmo y directamente en el navegador.',
'começar pela trilha 1 →':'empezar por la ruta 1 →','~20 min por sessão · 5 trilhas · 21 aulas · sem instalar nada · funciona no celular e no computador':'~20 min por sesión · 5 rutas · 21 clases · sin instalar nada · funciona en el móvil y el ordenador',
'O que você sai sabendo fazer':'Lo que sabrás hacer','Resultado, não teoria':'Resultados, no teoría',
'Escrever o objetivo com número':'Escribir un objetivo medible','— "de 3 em 100 para 5 em 100", e não "melhorar as vendas". É a primeira das cinco respostas que montam o loop.':'— «de 3 de cada 100 a 5 de cada 100», no «mejorar las ventas». Es la primera de las cinco respuestas que configuran el ciclo.',
'Transformar resultado em evidência':'Convertir resultados en evidencia','— uma planilha de registro, uma linha por proposta, chamado ou post, que o loop lê toda semana.':'— una hoja de seguimiento con una fila por propuesta, solicitud o publicación, que el ciclo lee cada semana.',
'Definir o que nunca muda sozinho':'Definir lo que nunca cambia por sí solo','— os guarda-corpos: o que a IA não pode tocar e o que não pode piorar enquanto melhora o resto.':'— las barreras: lo que la IA no puede tocar y lo que no debe empeorar mientras mejora lo demás.',
'Decidir com o cartão de cinco linhas':'Decidir con la tarjeta de cinco líneas','— aprovar, rejeitar ou esperar mais dados, sabendo qual quantidade prova e qual só parece.':'— aprobar, rechazar o esperar más datos, sabiendo qué cantidad aporta evidencia y cuál solo lo parece.',
'Dizer o que o loop não garante':'Saber qué no garantiza el ciclo','— e por isso confiar no que ele garante: nenhuma versão pior entra, tudo fica registrado, dá para voltar.':'— para confiar en lo que sí garantiza: no se publica una versión peor, todo queda registrado y se puede volver atrás.',
'Este curso não promete que o seu número sobe. Promete que ele não cai por decisão de um sistema, que cada tentativa fica registrada, e que você saberá dizer qual evidência faria você descartar a própria ideia.':'Este curso no promete que tus cifras aumenten. Promete que no caerán por decisión de un sistema, que cada intento quedará registrado y que sabrás qué evidencia te haría descartar tu propia idea.',
'Para quem é':'Para quién es','Feito para o seu momento':'Hecho para tu momento','é para você se':'es para ti si','não é para você se':'no es para ti si',
'Você é dona de clínica, corretor de imóveis, gestor de suporte — ou toca qualquer negócio onde a mesma tarefa se repete toda semana — e já usa IA para fazer propostas, respostas ou posts.':'Tienes una clínica, trabajas en bienes raíces, gestionas soporte o diriges cualquier negocio donde una tarea se repite cada semana, y ya usas IA para preparar propuestas, respuestas o publicaciones.',
'Você sente que a IA faz, mas nada melhora: a proposta de hoje começa do zero, como a de seis meses atrás.':'Sientes que la IA hace el trabajo, pero nada mejora: la propuesta de hoy empieza desde cero, igual que la de hace seis meses.',
'Você usa WhatsApp, planilha e um chat de IA. Nunca abriu uma tela preta de comandos e não pretende.':'Usas WhatsApp, hojas de cálculo y un chat de IA. Nunca has abierto una pantalla negra de comandos y no piensas hacerlo.',
'Você tem 20 minutos por sessão e prefere sair de cada aula com uma coisa preenchida.':'Tienes 20 minutos por sesión y prefieres terminar cada clase con algo completado.',
'Você quer aprender a programar agentes ou a integrar sistemas — este curso é sobre o método e a decisão, não sobre código.':'Quieres aprender a programar agentes o integrar sistemas: este curso enseña el método y la toma de decisiones, no programación.',
'Você quer um curso de prompts. Aqui os prompts são peças de um sistema, não o sistema.':'Quieres un curso sobre prompts. Aquí los prompts son piezas de un sistema, no el sistema en sí.',
'Você quer um curso com vídeo-aula tradicional.':'Quieres un curso con clases tradicionales en video.','Trilhas':'Rutas','Do diagnóstico ao seu loop montado':'Del diagnóstico a tu ciclo listo',
'Por que sua empresa não melhora':'Por qué tu empresa no mejora','Saia com a lista das cinco tarefas que "terminam ali" no seu negócio e o seu nível de maturidade (1 a 5) marcado.':'Termina con una lista de cinco tareas de tu negocio que «terminan ahí» y con tu nivel de madurez marcado (del 1 al 5).',
'O LOOP-R: localizar, operar, observar, propor, reforçar':'LOOP-R: localizar, operar, observar, proponer, reforzar','Saia com o objetivo escrito com número, dez linhas na planilha de registro e três hipóteses no formato SE… ENTÃO… PORQUE.':'Termina con un objetivo medible, diez filas en la hoja de seguimiento y tres hipótesis en el formato SI… ENTONCES… PORQUE.',
'Os assistentes do loop':'Los asistentes del ciclo','Saia com os guarda-corpos escritos — três coisas que nunca mudam sozinhas, duas que não podem piorar — e a primeira linha da sua memória.':'Termina con las barreras por escrito —tres cosas que nunca cambian solas y dos que no deben empeorar— y la primera entrada de tu memoria.',
'Medir de verdade':'Medir de verdad','Saia sabendo qual quantidade prova, com uma lista de conferência sim/não para o seu artefato, e tendo decidido sobre três cartões reais.':'Termina sabiendo qué tamaño de muestra aporta evidencia, con una lista sí/no para tu resultado y habiendo decidido sobre tres tarjetas reales.',
'Da tarefa à empresa':'De la tarea a la empresa','Saia com a ficha do loop completa — as cinco respostas — e o primeiro cartão de decisão preenchido. É a entrega final.':'Termina con la ficha del ciclo completa —las cinco respuestas— y tu primera tarjeta de decisión rellenada. Ese es el resultado final.',
'aulas':'clases','começar agora →':'empezar ahora →','Quer ver a ferramenta antes do curso? O guia do LOOP-R está em':'¿Quieres ver la herramienta antes del curso? La guía de LOOP-R está en',
'LOOP-R: Sua Empresa que Aprende Sozinha · INEMA.CLUB PRO':'LOOP-R: Tu empresa aprende por sí sola · INEMA.CLUB PRO'
}
for lang,mp in [('en',en),('es',es)]:
 p=root/'curso'/lang/'index.html'; s=p.read_text()
 for a,b in mp.items(): s=s.replace(a,b)
 # Ensure course selector is accessible and visible
 s=s.replace('<p class="language-links">','<nav class="language-links" aria-label="Language"><a href="../">PT</a> · <a href="../en/" lang="en">EN</a> · <a href="../es/" lang="es">ES</a></nav>')
 s=s.replace('</nav>\n</body>','</nav>\n</body>')
 p.write_text(s)
# Add language selector to the Portuguese README without changing its source content.
p=root/'README.md'; s=p.read_text(); line='\n**🇧🇷 [Português](README.md) · 🇺🇸 [English](README.en.md) · 🇪🇸 [Español](README.es.md)**\n'
if 'English](README.en.md)' not in s: s=s.replace('\n\n> ',line+'\n> ',1)
p.write_text(s)
